const categories = {
  djs: [
    "Martin Garrix",
    "David Guetta",
    // "Dimitri Vegas & Like Mike",
    "Alok",
    "Timmy Trumpet",
    "Armin Van Buuren",
    "Afrojack",
    "FISHER",
    "Vintage Culture",
    "Peggy Gou",
    "Hardwell",
    "Steve Aoki",
    "Alan Walker",
    "KSHMR",
    "Don Diablo",
    "Charlotte de Witte",
    "Anyma",
    "R3HAB",
    "Skrillex",
    "Lost Frequencies",
    "W&W",
    "Calvin Harris",
    "Tiësto",
    "Black Coffee",
    "Nicky Romero",
    "Reinier Zonneveld",
    "Vini Vici",
    "Fred again..",
    "Oliver Heldens",
    "Jamie Jones",
    "Carl Cox",
    "Claptone",
    "DJ Snake",
    "Marshmello",
    "Keinemusik",
    "Joel Corry",
    "Paul van Dyk",
    "Quintino",
    "Swedish House Mafia",
    "Fedde Le Grand",
    "Amelie Lens",
    "The Chainsmokers",
    "Alesso",
    "Bassjackers",
    "GORDO",
    "Eric Prydz",
    "ATB",
    "KAAZE",
    "Indira Paganotto",
    "NERVO",
    "Mariana Bo",
    "VINAI",
    "Above & Beyond",
    "Zedd",
    "Boris Brejcha",
    "KURA",
    "James Hype",
    "Deborah De Luca",
    "Tujamo",
    "Korolova",
    "Mochakk",
    "Dubdogz",
    "Julian Jordan",
    "Burak Yeter",
    "Nora En Pure",
    "Dom Dolla",
    "Deadmau5",
    "The Martinez Brothers",
    "Maddix",
    "John Summit",
    "Lucas & Steve",
    "Danny Avila",
    "Mike Williams",
    "22Bullets",
    "Sara Landry",
    "DubVision",
    "Cat Dealers",
    "Kölsch",
    "Liu",
    "Ferry Corsten",
    "Plastik Funk",
    "Jax Jones",
    "Le Twins",
    "Tungevaag",
    "ARYUE",
    "REZZ",
    "WUKONG",
    "Solomun",
    "Cuebrick",
    "MARNIK",
    "Mau P",
    "KAKA",
    "Pink Panda",
    "Naeleck",
    "Rave Republic",
    "Topic",
    "Giuseppe Ottaviani",
    "Faustix",
    "MEDUZA",
  ],

  actors: [
    "Leonardo DiCaprio",
    "Brad Pitt",
    "Robert De Niro",
    "Tom Hanks",
    "Morgan Freeman",
    "Johnny Depp",
    "Scarlett Johansson",
    "Chris Hemsworth",
    "Jennifer Lawrence",
    "Will Smith",
    "Denzel Washington",
    "Tom Cruise",
    "Natalie Portman",
    "Emma Stone",
    "Gal Gadot",
    "Ryan Reynolds",
    "Viola Davis",
    "Julia Roberts",
    "Angelina Jolie",
    "Matt Damon",
    "Joaquin Phoenix",
    "Kate Winslet",
    "Anne Hathaway",
    "Idris Elba",
    "Michael B. Jordan",
    "Robert Downey Jr.",
    "Margot Robbie",
    "Chris Evans",
    "Harrison Ford",
    "Samuel L. Jackson",
    "Mark Ruffalo",
    "Morgan Freeman",
    "Chris Pratt",
    "Keanu Reeves",
    "Zendaya",
    "Timothée Chalamet",
    "Florence Pugh",
    "Emma Watson",
    "Benicio del Toro",
    "Meryl Streep",
    "Nicole Kidman",
    "Kirsten Dunst",
    "Michael Caine",
    "George Clooney",
    "Lupita Nyong'o",
    "Ryan Gosling",
    "Chadwick Boseman", // note: conditional on if you want those passed
    "Amy Adams",
    "Jared Leto",
    "Hugh Jackman",
    "Emily Blunt",
    "Saoirse Ronan",
    "Tom Holland",
    "Jason Momoa",
    "Pedro Pascal",
    "Chris Pine",
    // You can expand or swap depending on region / popularity
  ],

  influencers: [
    "MrBeast",
    "Selena Gomez",
    "Kylie Jenner",
    "Kim Kardashian",
    "Beyoncé",
    "Ariana Grande",
    "Taylor Swift",
    "Justin Bieber",
    "Dwayne Johnson",
    "LeBron James",
    "Charli D'Amelio",
    "Addison Rae",
    "Emma Chamberlain",
    "Rhett & Link",
    "Loren Gray",
    "Jake Paul",
    "David Dobrik",
    "Markiplier",
    "PewDiePie",
    "Jacksepticeye",
    "Dude Perfect",
    "Logan Paul",
    "MrBeast",
    "Lilly Singh",
    "James Charles",
    "NikkieTutorials",
    "Zach King",
    "Khloé Kardashian",
    "Kendall Jenner",
    "Ninja", // gamer
    "Shane Dawson",
    "JoJo Siwa",
    "Lele Pons",
    "Liza Koshy",
    "Huda Kattan",
    "Rihanna",
    "Nicki Minaj",
    "K-pop stars like BTS",
    // Expand / localize as you want
  ],

  athletes: [
    "Lionel Messi",
    "Cristiano Ronaldo",
    "LeBron James",
    "Serena Williams",
    "Rafael Nadal",
    "Roger Federer",
    "Tiger Woods",
    "Usain Bolt",
    "Michael Jordan",
    "Muhammad Ali",
    "Novak Djokovic",
    "Conor McGregor",
    "Simone Biles",
    "Stephen Curry",
    "Tom Brady",
    "Lewis Hamilton",
    "Megan Rapinoe",
    "Naomi Osaka",
    "Lindsey Vonn",
    "Shohei Ohtani",
    "Katie Ledecky",
    "Shaquille O Neal",
    "Giannis Antetokounmpo",
    "Tom Daley",
    "Allyson Felix",
    "Caeleb Dressel",
    "Virat Kohli",
    "Kylian Mbappé",
    "Mike Trout",
    // can extend by sport, region etc.
  ],

  // You can add more categories people enjoy, e.g.:
  // musicians (non-DJ), fictional characters, scientists, landmarks, etc.
};
